import type { SkillManifest, BuildOutput } from "./types";

export async function buildSkill(skillDir: string): Promise<BuildOutput[]> {
  const manifestFile = Bun.file(`${skillDir}/manifest.json`);
  if (!(await manifestFile.exists())) {
    throw new Error("manifest.json not found in " + skillDir);
  }

  const manifest: SkillManifest = await manifestFile.json();
  const entryFile = Bun.file(`${skillDir}/${manifest.core_logic.entry}`);
  if (!(await entryFile.exists())) {
    throw new Error(`Entry file '${manifest.core_logic.entry}' not found`);
  }

  const content = await entryFile.text();
  const outputs: BuildOutput[] = [];

  for (const target of manifest.targets) {
    if (target === "claude") {
      outputs.push(buildForClaude(manifest, content));
    } else if (target === "openclaw") {
      outputs.push(buildForOpenClaw(manifest, content));
    }
  }

  return outputs;
}

function buildForClaude(manifest: SkillManifest, content: string): BuildOutput {
  // Claude Code skill format: markdown file in ~/.claude/skills/
  const header = [
    `---`,
    `# Auto-generated by SkillForge v${manifest.version}`,
    `# ID: ${manifest.id}`,
    `# Tags: ${manifest.metadata.tags.join(", ")}`,
    `---`,
    ``,
  ].join("\n");

  return {
    target: "claude",
    path: `${homedir()}/.claude/skills/${manifest.id}.md`,
    content: header + content,
  };
}

function buildForOpenClaw(manifest: SkillManifest, content: string): BuildOutput {
  // OpenClaw skill format: directory with skill.json + skill content
  const skillJson = {
    name: manifest.name,
    id: manifest.id,
    version: manifest.version,
    description: manifest.description,
    author: manifest.author,
    tags: manifest.metadata.tags,
    category: manifest.metadata.category,
    dependencies: manifest.dependencies.tools,
    quality: manifest.quality_metrics,
  };

  // For OpenClaw, we output the JSON manifest
  // The content file is copied separately in the deploy step
  return {
    target: "openclaw",
    path: `${homedir()}/.openclaw/skills/${manifest.id}/skill.json`,
    content: JSON.stringify(skillJson, null, 2),
  };
}

function homedir(): string {
  return process.env.USERPROFILE || process.env.HOME || "~";
}

export async function deployBuild(outputs: BuildOutput[]): Promise<string[]> {
  const deployed: string[] = [];

  for (const output of outputs) {
    const dir = output.path.substring(0, output.path.lastIndexOf("/"));
    await Bun.write(output.path, output.content);
    deployed.push(output.path);
  }

  return deployed;
}
